### ISSUE TITLE
Crash related to despawning entity

### ISSUE THREAD

**Issue by RJ** [Jondolf/bevy_xpbd#69]
I have a short lived bullet, when it gets despawned using `commands.entity(entity).despawn();` i get a crash:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/rj/src/bevy_xpbd/crates/bevy_xpbd_2d/../../src/plugins/spatial_query/pipeline.rs:82:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_xpbd_2d::plugins::spatial_query::update_query_pipeline`!
Encountered a panic in exclusive system `bevy_xpbd_2d::plugins::setup::run_physics_schedule`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/rj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.11.0/src/pipelined_rendering.rs:110:77
```

might need to check in there that the entity still has a collider - i suppose it doesn't if it's being despawned?

not exactly sure what triggers it, but happens pretty soon if i fly around blasting bullets that are set to despawn after a second or so.

**Comment by Jondolf** [comment]
This should hopefully be fixed in a PR coming very soon. You can already try if it works on the `spatial-query-fixes` branch. You can specify the dependency like this:

```toml
[dependencies]
bevy_xpbd_2d = { git = "https://github.com/Jondolf/bevy_xpbd", branch = "spatial-query-fixes" }
```
```
